### ISSUE TITLE
hi,now i am facing a problem when i ran ./run_test.sh

### ISSUE THREAD

**Issue by F0Wen** [ucbdrive/3d-vehicle-tracking#18]
File "test_net.py", line 304, in <module>
    RCNN_loss_center, rois_label = fasterRCNN(im_data, im_info, gt_boxes,num_boxes, fixed_center)
  File "/home/ld/.conda/envs/dave/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ld/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/faster_rcnn/faster_rcnn.py", line 46, in forward
    base_feat = self.RCNN_base(im_data)
  File "/home/ld/.conda/envs/dave/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ld/.conda/envs/dave/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/ld/.conda/envs/dave/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ld/.conda/envs/dave/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/ld/.conda/envs/dave/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ld/3d-vehicle-tracking/faster-rcnn.pytorch/lib/model/faster_rcnn/resnet.py", line 86, in forward
    out = self.conv1(x)
  File "/home/ld/.conda/envs/dave/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ld/.conda/envs/dave/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA error: out of memory

**Comment by chrisHuxi** [comment]
It is exactly as the msg said: CUDA out of memory
I have this issue before too, my GPU is GTX1060 6GB, it is still not sufficient to load faster-rcnn model.
So I would suggest you either use a GPU with more mem., or you use the detection result from the author.

**Comment by F0Wen** [comment]
Thanks! i have solved this problem by change a GPU with 9GB!

**Comment by kunshou123** [comment]
hi ,I run mono_3d_tracking.py  
/home/work/3d-vehicle-tracking-master/3d-tracking/mono_3d_estimation.py gta test --data_split val --json_path /home/work/3d-vehicle-tracking-master/3d-tracking/data/gta5_tracking/val/label/rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd.json -j 2 -b 1 --n_box_limit 300 --resume ./checkpoint/616_gta_checkpoint_030.pth.tar
Using RoIAlign
=> Loading checkpoint './checkpoint/616_gta_checkpoint_030.pth.tar'
=> Successfully loaded checkpoint './checkpoint/616_gta_checkpoint_030.pth.tar' (epoch 30)
Reading /home/gejun/work/3d-vehicle-tracking-master/3d-tracking/data/gta5_tracking/val/label/rec_10090911_clouds_21h53m_x-968y-1487tox2523y214_bdd.json ...
Load single json file
Sequences [463] with total 463 frames
Input images are not normalized
Number of image to test: 463
0
1
Traceback (most recent call last):
  File "/home/work/3d-vehicle-tracking-master/3d-tracking/mono_3d_estimation.py", line 539, in <module>
    main()
  File "/home/work/3d-vehicle-tracking-master/3d-tracking/mono_3d_estimation.py", line 535, in main
    test_model(model, args)
  File "/home/work/3d-vehicle-tracking-master/3d-tracking/mono_3d_estimation.py", line 426, in test_model
    for i, (image, box_info) in enumerate(iter(test_loader)):
  File "/home/anaconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/anaconda3/envs/pytorch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
TypeError: __init__() missing 2 required positional arguments: 'doc' and 'pos'

Process finished with exit code 1
========================================
I find the code can iter 2 times normally ,then it broken ,can you give me some advice to solve it???

for i, (image, box_info) in enumerate(iter(test_loader)):
        # measure data loading time
        data_time.update(time.time() - end)        
         end = time.time()

        with torch.no_grad():
            box_output, targets = model(image, box_info, args.device, 'test')

        batch_time.update(time.time() - end)
=======================================================
